"""Download every image the app references into assets/images/ and generate
lib/asset_images.dart (a URL -> bundled-asset map).

Why: bundling images makes the app load instantly, work offline, and removes the
runtime dependency on a remote server / image proxy — which is exactly what the
App Store / Play Store prefer, and avoids review issues.

Re-run whenever image URLs change:
    backend/.venv/Scripts/python.exe strikin_flutter/tool/fetch_images.py
(uses the backend venv because it has `truststore` for TLS behind SSL inspection)
"""
import hashlib
import os
import re
import ssl
import urllib.request
from pathlib import Path

try:
    import truststore
    truststore.inject_into_ssl()  # use OS trust store (works behind corp SSL inspection)
except Exception:
    pass

ROOT = Path(__file__).resolve().parents[1]          # strikin_flutter/
LIB = ROOT / "lib"
ASSETS = ROOT / "assets" / "images"
API = os.environ.get("STRIKIN_API", "http://localhost:8000")
SANITY = "https://cdn.sanity.io/images/y370h02s/production"

URL_RE = re.compile(r"https://[^\s\"')]+", re.I)
# Bare Sanity asset filenames (e.g. '71e8...d7-1920x1080.png'), referenced either
# directly via _img('...') or inside data tuples as plain strings.
SANITY_FILE_RE = re.compile(r"([0-9a-f]{40}-[0-9x]+\.(?:png|jpe?g|webp))", re.I)


def collect_urls() -> set[str]:
    urls: set[str] = set()

    # 1) From the live API (activities, bays, food) — the data-driven images.
    import json
    def get(path):
        try:
            with urllib.request.urlopen(f"{API}{path}", timeout=8) as r:
                return json.load(r)
        except Exception as e:
            print(f"  (skip {path}: {e})")
            return []
    for a in get("/activities"):
        if a.get("image"):
            urls.add(a["image"])
        for b in get(f"/activities/{a['slug']}/bays"):
            if b.get("image"):
                urls.add(b["image"])
    for f in get("/food"):
        if f.get("image"):
            urls.add(f["image"])

    # 2) From the Dart source (mock fallbacks + hardcoded hero/info images).
    for dart in LIB.rglob("*.dart"):
        text = dart.read_text(encoding="utf-8", errors="ignore")
        for u in URL_RE.findall(text):
            if any(k in u for k in ("unsplash", "sanity", ".png", ".jpg", ".jpeg", ".webp")):
                urls.add(u)
        for fname in SANITY_FILE_RE.findall(text):
            urls.add(f"{SANITY}/{fname}?w=1200&q=80")
    return urls


def normalize(url: str) -> str:
    """Key = URL without the resize query string (identifies the unique image)."""
    return url.split("?", 1)[0]


def best_download_url(key: str) -> str:
    """Request a good resolution for the bundled copy."""
    if "sanity" in key:
        return f"{key}?w=1200&q=80"
    if "unsplash" in key:
        return f"{key}?w=900&q=80"
    return key


def ext_of(key: str) -> str:
    m = re.search(r"\.(png|jpe?g|webp|gif)$", key, re.I)
    return ("." + m.group(1).lower()) if m else ".jpg"


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    keys = sorted({normalize(u) for u in collect_urls()})
    print(f"Found {len(keys)} unique images. Downloading -> {ASSETS}")
    ctx = ssl.create_default_context()
    mapping: dict[str, str] = {}
    ok = 0
    for key in keys:
        fname = hashlib.sha1(key.encode()).hexdigest()[:16] + ext_of(key)
        dest = ASSETS / fname
        rel = f"assets/images/{fname}"
        if not dest.exists():
            try:
                req = urllib.request.Request(best_download_url(key), headers={"User-Agent": "Mozilla/5.0"})
                with urllib.request.urlopen(req, timeout=20, context=ctx) as r:
                    dest.write_bytes(r.read())
            except Exception as e:
                print(f"  FAIL {key[:60]}... : {e}")
                continue
        mapping[key] = rel
        ok += 1
        print(f"  ok  {rel}  <-  {key[:70]}")

    # Generate the Dart map.
    out = LIB / "asset_images.dart"
    lines = [
        "// GENERATED by tool/fetch_images.py — do not edit by hand.",
        "// Maps a remote image URL (without its ?query) to a bundled asset path.",
        "const Map<String, String> kAssetForUrl = {",
    ]
    for k in sorted(mapping):
        lines.append(f"  {k!r}: {mapping[k]!r},")
    lines.append("};")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nDownloaded {ok}/{len(keys)} images.")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
